export const RADIO_STATIONS = {
  "The Blue Ark": "/images/radios/theBlueArk.webp",
  "WorldWide FM": "/images/radios/worlwideFM.webp",
  "FlyLo FM": "/images/radios/flyloFM.webp",
  "The Lowdown 91.1": "/images/radios/lowdownFM.webp",
  "Radio Mirror Park": "/images/radios/radioMirrorFM.webp",
  "Space 103.2": "/images/radios/spaceFM.webp",
  "Vinewood Boulevard Radio": "/images/radios/vinewoodFM.webp",
  "Los Santos Rock Radio": "/images/radios/rockRadioFm.webp",
  "Non-Stop-Pop FM": "/images/radios/nonStopFM.webp",
  "Radio Los Santos": "/images/radios/radioLosSantos.webp",
  "Channel X": "/images/radios/channelX.webp",
  "Rebel Radio": "/images/radios/rebelFm.webp",
  "Soulwax FM": "/images/radios/soulwax.webp",
  "West Coast Classics": "/images/radios/westFm.webp",
  "The Lab": "/images/radios/thelab.webp",
  "Blonded Los Santos 97.8 FM": "/images/radios/blonded.webp",
  "Los Santos Underground Radio": "/images/radios/underground.png",
  "East Los FM": "/images/radios/east.webp",
  "iFruit Radio": "/images/radios/fruit.png",
  "Kult FM 99.1": "/images/radios/kult.png",
  "Still Slipping Los Santos": "/images/radios/slipping.png",
  "Music Locker Radio": "/images/radios/locker.png",
  "Reproductor": "/images/radios/reproductor.webp",
  "MOTOMAMI Los Santos": "/images/radios/motomami.png",
};
